services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - GO_ENV=${GO_ENV:-development}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped